site_name: EDA technical academy
site_author: Jerome Boyer
repo_url: https://github.com/ibm-cloud-architecture/eda-tech-academy
remote_branch: gh-pages
remote_name: origin
nav:
  - Introduction: index.md
  - Information:
    - Why EDA now?: eda.md
    - Fit for purpose: https://ibm-cloud-architecture.github.io/refarch-eda/concepts/fit-to-purpose/
    - EDA Reference Architecture: https://ibm-cloud-architecture.github.io/refarch-eda/introduction/reference-architecture/#event-driven-architecture
  - Journey 1:
    - Getting started with Event Streams: getting-started/index.md
    - Event Streams schema: getting-started/schema-lab.md
    - Demonstration A to Z: demo/index.md
    - System Design Lab:
      - Problem Statement: lab1/index.md
      - Solution Overview: lab1/lab1-sol.md
  - Journey 2:
    - Lab 1 - System Design Lab:
      - Problem Statement: lab1/index.md
      - Solution Overview: lab1/lab1-sol.md
    - Kafka Streams Lab:
      - Kafka Streams Study: lab2/kstream.md
      - Lab 2 exercises: lab2/index.md
      - Solution Overview: lab2/lab2-sol.md
    - Lab 3 - Real Time Inventory demo: lab3/index.md
    - Lab 4 - EDA GitOps: lab4/index.md
    - Lab 5 - Monitoring with Instana: lab5/index.md
  - More...: future.md

theme: 
  name: material
  # custom_dir: docs/overrides
  palette:
    scheme: default
  language: en
  include_search_page: false
  search_index_only: true
  features:
      - content.code.annotate
      - content.tooltips
      - navigation.tabs
      - navigation.instant
      # - navigation.indexes
      - navigation.sections
      - navigation.expand
      #- navigation.tracking
      - navigation.tabs.sticky

extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - meta
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
