site_name: EDA technical academy
site_author: Jerome Boyer
repo_url: https://github.ibm.com/boyerje/eda-tech-academy

nav:
  - Introduction: index.md
  - Information:
    - Why EDA now?: eda.md
    - Fit for purpose: https://ibm-cloud-architecture.github.io/refarch-eda/concepts/fit-to-purpose/
    - EDA Reference Architecture: https://ibm-cloud-architecture.github.io/refarch-eda/introduction/reference-architecture/#event-driven-architecture
  - Track 1 - Beginner Lab: lab0/
  - Track 1 | 2 - Lab 1 System Design:
    - Problem Statement: lab1/index.md
    - Solution Overview: lab1/lab1-sol.md
  - Track 2 - Lab 2 Kafka Streams:
    - Kafka Streams Study: lab2/kstream.md
    - Problem Statement: lab2/index.md
    - Solution Overview: lab2/lab2-sol.md
  - Track 2 - Lab 3 Running demo: lab3/index.md
  - Track 2 - Lab 4 GitOps: lab4/index.md
  - Future: future.md

theme: 
  name: material
  # custom_dir: docs/overrides
  palette:
    scheme: default
  language: en
  include_search_page: false
  search_index_only: true
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.indexes
      - navigation.tracking
      - navigation.tabs.sticky

extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - meta
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
