site_name: EDA technical academy
repo_url: https://github.ibm.com/boyerje/eda-tech-academy
nav:
  - Preparation:
    - Why EDA now?: eda.md
    - Event Streams Demo from A to Z: https://pages.github.ibm.com/boyerje/eda-internal/demo/demo-script/
    - Fit for purpose: https://ibm-cloud-architecture.github.io/refarch-eda/concepts/fit-to-purpose/
    - Reference Architecture: https://ibm-cloud-architecture.github.io/refarch-eda/introduction/reference-architecture/#event-driven-architecture
  - Lab 1 System Design:
    - Problem Statement: lab1/index.md
    - Solution Overview: lab1/lab1-sol.md
  - Lab 2 Item inventory:
    - Problem Statement: lab2.md
    - Solution Overview: lab2-sol.md
  - Lab 3 Running demo: lab3.md
  - Lab 4 GitOps: gitops.md
  - Future: future.md

theme: 
  name: material
  feature:
    tabs: true
  palette:
    scheme: default
    primary: 'magenta dark'
  language: en
  features:
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      - navigation.tabs.sticky
      - navigation.left
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.details