apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: std-1-ns
  namespace: openshift-gitops
spec:
  destination:
    namespace: std-1
    server: https://kubernetes.default.svc
  project: std-1
  source:
    path: lab3/env/overlays
    repoURL: https://github.ibm.com/boyerje/eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
