apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: es-service-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: std-1
    server: https://kubernetes.default.svc
  project: std-1
  source:
    path: lab3-4/services/ibm-eventstreams/overlays
    repoURL: https://github.com/jbcodeforce/eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
