apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: item-inventory
  name: item-inventory-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: std-1-inventory
    server: https://kubernetes.default.svc
  project: std-2
  source:
    path: lab3/apps/item-inventory/overlays
    repoURL: https://github.ibm.com/boyerje/eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

