apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: std-1-rt-inventory
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - "if [ -z '$(kubectl get secret ibm-entitlement-key | grep found)' ]; \
          then kubectl get secret ibm-entitlement-key -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"std-1-rt-inventory\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.creationTimestamp)'  \
          | kubectl apply -f - ;\
          else echo already_created; fi"
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
